<a href="https://colab.research.google.com/github/Suchada2000/MY-WORK/blob/main/Untitled45.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd

# อ่านไฟล์ Excel
df = pd.read_excel('/content/sample_data/Untitled spreadsheet.xlsx')

In [2]:

# แปลงคอลัมน์ DATESALE เป็น datetime โดยไม่ระบุ format และจัดการกับข้อผิดพลาด
df['DATESALE'] = pd.to_datetime(df['DATESALE'], errors='coerce')

# แปลงให้เป็นรูปแบบ YYYY-MM-DD
df['DATESALE'] = df['DATESALE'].dt.strftime('%Y-%m-%d')

In [12]:
print(df.dtypes)

ID_Card                       int64
AGE                           int64
Premium                     float64
DATESALE             datetime64[ns]
INCDTE               datetime64[ns]
DATREP               datetime64[ns]
DATOCC               datetime64[ns]
ReseveDescription            object
GRS_OS                      float64
GRS_PAID                    float64
GIC                         float64
Other                        object
dtype: object

In [4]:

# แปลงคอลัมน์ DATESALE เป็น string แล้วค่อยแปลงเป็น datetime โดยระบุ format
df['INCDTE'] = pd.to_datetime(df['INCDTE'].astype(str), format='%Y%m%d', errors='coerce')

# แปลงให้เป็นรูปแบบ YYYY-MM-DD
df['INCDTE'] = df['INCDTE'].dt.strftime('%Y-%m-%d')

In [5]:

# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df['DATREP'] = pd.to_datetime(df['DATREP'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df['DATREP'] = df['DATREP'].dt.strftime('%Y-%m-%d')

# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df['DATOCC'] = pd.to_datetime(df['DATOCC'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df['DATOCC'] = df['DATOCC'].dt.strftime('%Y-%m-%d')

In [7]:

# แปลงเป็น datetime โดยให้ pandas จัดการรูปแบบอัตโนมัติ
df['DATESALE'] = pd.to_datetime(df['DATESALE'], format='mixed', errors='coerce')
df['INCDTE'] = pd.to_datetime(df['INCDTE'], format='mixed', errors='coerce')

In [11]:

# แปลงเป็น datetime โดยให้ pandas จัดการรูปแบบอัตโนมัติ
df['DATOCC'] = pd.to_datetime(df['DATOCC'], format='mixed', errors='coerce')
df['DATOCC'] = pd.to_datetime(df['DATOCC'], format='mixed', errors='coerce')

In [13]:
df

,ID_Card,AGE,Premium,DATESALE,INCDTE,DATREP,DATOCC,ReseveDescription,GRS_OS,GRS_PAID,GIC,Other
0,2,34,3170.50,2023-10-07,2023-11-02,2024-02-13,2024-01-22,Trip Cancellation Coverage,0.0,5970.00,5970.00,Y
1,8,35,6953.00,2023-09-21,2023-10-01,2024-07-01,2024-06-01,Flight Delay Coverage,0.0,28000.00,28000.00,Y
2,7,35,6953.00,2023-09-21,2023-10-01,2024-10-02,2024-09-27,Baggage Delay Coverage,0.0,35000.00,35000.00,Y
3,2,34,3170.50,2023-10-07,2023-11-02,2024-02-13,2024-01-22,Baggage & Personal Effects,0.0,3570.00,3570.00,Y
4,19,40,1134.75,2023-11-29,2023-11-29,2023-12-08,2023-12-01,Daily Benefits,0.0,18000.00,18000.00,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
38312,254010159,55,1570.50,2024-03-29,2024-08-04,2024-10-30,2024-08-07,GP/A Medical Expense,2000.0,16749.58,18749.58,N
38313,254010159,55,1570.50,2024-03-29,2024-08-04,2024-10-30,2024-08-07,Transportation Cost for OPD,0.0,1000.00,1000.00,N
38314,254010160,49,3357.00,2023-02-07,2023-07-26,2023-08-22,2023-08-03,Baggage Delay Coverage,0.0,3000.00,3000.00,N
38315,254010160,49,3357.00,2023-02-07,2023-07-26,2023-11-17,2023-10-22,Baggage & Personal Effects,1.0,0.00,1.00,N
38316,254010160,49,3357.00,2023-02-07,2023-07-26,2023-12-13,2023-07-31,Rental Vehicle Excess,0.0,15000.00,15000.00,N

In [14]:

# บันทึก DataFrame เป็นไฟล์ Excel
df.to_excel('CLAIM_TA_date.xlsx', index=False)