<a href="https://colab.research.google.com/github/Suchada2000/MY-WORK/blob/main/Untitled42.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [138]:

import pandas as pd

# อ่านไฟล์ Excel
df = pd.read_excel('/content/sample_data/CLAIM_TA.xlsx')

In [139]:
import numpy as np
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

<ipython-input-139-83f14fa381f3>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

In [140]:
df.isnull().sum()

Dummy ID                 0
AGE                      0
SEX                  29467
Occupation           16790
Policy_Class             0
Plan_                  543
Premium                  0
DATESALE               543
INCDTE                   0
ExpireDate               0
DATREP                   0
DATOCC                   0
ReserveCode              0
ReseveDescription       30
GRS_OS                   0
GRS_PAID                 0
GIC                      0
dtype: int64

In [141]:
# สมมติว่า df เป็น DataFrame ของคุณ

# ตารางที่มี Plan_ เป็นค่าว่าง
df_missing = df[df['DATESALE'].isnull()]

# ตารางที่ไม่มี Plan_ เป็นค่าว่าง
df_not_missing = df[df['DATESALE'].notnull()]

# ตรวจสอบผลลัพธ์
print("ตารางที่มี Plan_ เป็นค่าว่าง:")
print(df_missing.head())

print("\nตารางที่ไม่มี Plan_ เป็นค่าว่าง:")
print(df_not_missing.head())

ตารางที่มี Plan_ เป็นค่าว่าง:
     Dummy ID  AGE  SEX                                       Occupation  \
30         41    0  NaN                                              NaN
31         42    0  NaN  EMPLOYEE
146       181    0  NaN                                              NaN
147       182    0  NaN                                              NaN
148       183    0  NaN  EMPLOYEE

    Policy_Class Plan_  Premium DATESALE    INCDTE  ExpireDate    DATREP  \
30           GAT   NaN   1708.0      NaT  20230324    20230327  20230410
31           GAT   NaN   1272.0      NaT  20241021    20241027  20241118
146          GAT   NaN    502.0      NaT  20230210    20230213  20230315
147          GAT   NaN   4200.0      NaT  20230310    20230313  20230412
148          GAT   NaN  19980.0      NaT  20231110    20231112  20231124

       DATOCC ReserveCode     ReseveDescription  GRS_OS  GRS_PAID      GIC
30   20230325          ME  GP/A Medical Expense     0.0    2407.0   2407.0
31   20241025          ME  GP/A Medical Expense     0.0    1202.0   1202.0
146  20230211          ME  GP/A Medical Expense     0.0       0.0      0.0
147  20230310          ME  GP/A Medical Expense     0.0    1680.0   1680.0
148  20231110          ME  GP/A Medical Expense     0.0   23690.0  23690.0

ตารางที่ไม่มี Plan_ เป็นค่าว่าง:
   Dummy ID  AGE  SEX                                       Occupation  \
0         1   40  NaN                                              NaN
1         2   75  NaN  EMPLOYEE
2         3   33  NaN                                              NaN
3         4   30  NaN                                              NaN
4         5   50  NaN                                              NaN

  Policy_Class                           Plan_  Premium            DATESALE  \
0          GDF  7U                                 80.0 2022-12-11 22:24:22
1          GDF  8Y                                160.0 2022-12-31 10:39:44
2          GDF  7ฉ                                100.0 2023-03-23 00:57:49
3          GDF  7ด                                180.0 2023-07-10 21:55:00
4          GDF  7ด                                180.0 2023-07-20 19:54:50

     INCDTE  ExpireDate    DATREP    DATOCC ReserveCode  \
0  20221231    20230101  20230711  20230101          VD
1  20230124    20230128  20230308  20230127          FD
2  20230323    20230324  20230329  20230323          FD
3  20230721    20230727  20230807  20230721          BD
4  20230725    20230730  20230803  20230725          BD

        ReseveDescription  GRS_OS  GRS_PAID     GIC
0      ค่ารักษาจากโควิค19     0.0       0.0     0.0
1   Flight Delay Coverage     0.0    2000.0  2000.0
2   Flight Delay Coverage     0.0    2000.0  2000.0
3  Baggage Delay Coverage     0.0       0.0     0.0
4  Baggage Delay Coverage     0.0    6000.0  6000.0

In [125]:
df_missing

,Dummy ID,AGE,SEX,Occupation,Policy_Class,Plan_,Premium,DATESALE,INCDTE,ExpireDate,DATREP,DATOCC,ReserveCode,ReseveDescription,GRS_OS,GRS_PAID,GIC
30,41,0,NaN,NaN,GAT,NaN,1708.0,NaT,20230324,20230327,20230410,20230325,ME,GP/A Medical Expense,0.00,2407.00,2407.00
31,42,0,NaN,EMPLOYEE,GAT,NaN,1272.0,NaT,20241021,20241027,20241118,20241025,ME,GP/A Medical Expense,0.00,1202.00,1202.00
146,181,0,NaN,NaN,GAT,NaN,502.0,NaT,20230210,20230213,20230315,20230211,ME,GP/A Medical Expense,0.00,0.00,0.00
147,182,0,NaN,NaN,GAT,NaN,4200.0,NaT,20230310,20230313,20230412,20230310,ME,GP/A Medical Expense,0.00,1680.00,1680.00
148,183,0,NaN,EMPLOYEE,GAT,NaN,19980.0,NaT,20231110,20231112,20231124,20231110,ME,GP/A Medical Expense,0.00,23690.00,23690.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9817,10311,43,NaN,EMPLOYEE,GWW,NaN,208618.0,NaT,20230721,20230926,20231220,20230802,ME,GP/A Medical Expense,0.00,166945.50,166945.50
9818,10312,25,NaN,EMPLOYEE,GWW,NaN,154123.0,NaT,20230721,20230926,20231220,20230801,ME,GP/A Medical Expense,0.00,9536.86,9536.86
9819,10313,44,NaN,EMPLOYEE,GWW,NaN,255796.0,NaT,20240717,20240930,20250129,20240902,ME,GP/A Medical Expense,1816.52,0.00,1816.52
9820,10314,50,NaN,EMPLOYEE,GWW,NaN,255796.0,NaT,20240717,20240930,20250129,20240828,ME,GP/A Medical Expense,14333.83,0.00,14333.83
9821,10315,54,NaN,EMPLOYEE,GWW,NaN,250747.0,NaT,20240719,20241002,20250129,20240819,ME,GP/A Medical Expense,8605.21,0.00,8605.21

In [126]:
df_not_missing

,Dummy ID,AGE,SEX,Occupation,Policy_Class,Plan_,Premium,DATESALE,INCDTE,ExpireDate,DATREP,DATOCC,ReserveCode,ReseveDescription,GRS_OS,GRS_PAID,GIC
0,1,40,NaN,NaN,GDF,7U,80.0,2022-12-11 22:24:22,20221231,20230101,20230711,20230101,VD,ค่ารักษาจากโควิค19,0.0,0.0,0.0
1,2,75,NaN,EMPLOYEE,GDF,8Y,160.0,2022-12-31 10:39:44,20230124,20230128,20230308,20230127,FD,Flight Delay Coverage,0.0,2000.0,2000.0
2,3,33,NaN,NaN,GDF,7ฉ,100.0,2023-03-23 00:57:49,20230323,20230324,20230329,20230323,FD,Flight Delay Coverage,0.0,2000.0,2000.0
3,4,30,NaN,NaN,GDF,7ด,180.0,2023-07-10 21:55:00,20230721,20230727,20230807,20230721,BD,Baggage Delay Coverage,0.0,0.0,0.0
4,5,50,NaN,NaN,GDF,7ด,180.0,2023-07-20 19:54:50,20230725,20230730,20230803,20230725,BD,Baggage Delay Coverage,0.0,6000.0,6000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33064,34534,49,NaN,EMPLOYEE,PWT,YF,765.0,2024-12-05 17:18:12,20241213,20241222,20250120,20241220,ME,GP/A Medical Expense,2000.0,0.0,2000.0
33065,34535,56,NaN,EMPLOYEE,PWT,YF,955.0,2024-12-09 17:52:50,20241212,20241224,20250115,20241214,LD,Damage or Loss of Travel Docum,2000.0,0.0,2000.0
33066,34536,47,NaN,EMPLOYEE,PWT,YE,490.0,2024-12-19 21:27:45,20241219,20241223,20250107,20241221,BP,Baggage & Personal Effects,2000.0,0.0,2000.0
33067,34537,51,NaN,NaN,PWT,YO,3730.0,2024-12-20 16:25:11,20241222,20251221,20250128,20250123,BP,Baggage & Personal Effects,2000.0,0.0,2000.0
33068,34538,78,NaN,EMPLOYEE,PWT,Q1,3110.0,2024-12-21 17:27:38,20241222,20250116,20250122,20250116,BD,Baggage Delay Coverage,2000.0,0.0,2000.0

⏰

df_not_missing

In [133]:
df_not_missing['DATESALE'] = pd.to_datetime(df_not_missing['DATESALE']).dt.strftime('%Y-%m-%d')

<ipython-input-133-6dff1fe3c491>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['DATESALE'] = pd.to_datetime(df_not_missing['DATESALE']).dt.strftime('%Y-%m-%d')

In [134]:
# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df_not_missing['INCDTE'] = pd.to_datetime(df_not_missing['INCDTE'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df_not_missing['INCDTE'] = df_not_missing['INCDTE'].dt.strftime('%Y-%m-%d')

# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df_not_missing['ExpireDate'] = pd.to_datetime(df_not_missing['ExpireDate'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df_not_missing['ExpireDate'] = df_not_missing['ExpireDate'].dt.strftime('%Y-%m-%d')

# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df_not_missing['DATREP'] = pd.to_datetime(df_not_missing['DATREP'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df_not_missing['DATREP'] = df_not_missing['DATREP'].dt.strftime('%Y-%m-%d')

# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df_not_missing['DATOCC'] = pd.to_datetime(df_not_missing['DATOCC'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df_not_missing['DATOCC'] = df_not_missing['DATOCC'].dt.strftime('%Y-%m-%d')

<ipython-input-134-b686a0ba1dad>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['INCDTE'] = pd.to_datetime(df_not_missing['INCDTE'].astype(str), format='%Y%m%d')
<ipython-input-134-b686a0ba1dad>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['INCDTE'] = df_not_missing['INCDTE'].dt.strftime('%Y-%m-%d')
<ipython-input-134-b686a0ba1dad>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['ExpireDate'] = pd.to_datetime(df_not_missing['ExpireDate'].astype(str), format='%Y%m%d')
<ipython-input-134-b686a0ba1dad>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['ExpireDate'] = df_not_missing['ExpireDate'].dt.strftime('%Y-%m-%d')
<ipython-input-134-b686a0ba1dad>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['DATREP'] = pd.to_datetime(df_not_missing['DATREP'].astype(str), format='%Y%m%d')
<ipython-input-134-b686a0ba1dad>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['DATREP'] = df_not_missing['DATREP'].dt.strftime('%Y-%m-%d')
<ipython-input-134-b686a0ba1dad>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['DATOCC'] = pd.to_datetime(df_not_missing['DATOCC'].astype(str), format='%Y%m%d')
<ipython-input-134-b686a0ba1dad>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['DATOCC'] = df_not_missing['DATOCC'].dt.strftime('%Y-%m-%d')

In [135]:
df_not_missing.head()

,Dummy ID,AGE,SEX,Occupation,Policy_Class,Plan_,Premium,DATESALE,INCDTE,ExpireDate,DATREP,DATOCC,ReserveCode,ReseveDescription,GRS_OS,GRS_PAID,GIC
0,1,40,NaN,NaN,GDF,7U,80.0,2022-12-11,2022-12-31,2023-01-01,2023-07-11,2023-01-01,VD,ค่ารักษาจากโควิค19,0.0,0.0,0.0
1,2,75,NaN,EMPLOYEE,GDF,8Y,160.0,2022-12-31,2023-01-24,2023-01-28,2023-03-08,2023-01-27,FD,Flight Delay Coverage,0.0,2000.0,2000.0
2,3,33,NaN,NaN,GDF,7ฉ,100.0,2023-03-23,2023-03-23,2023-03-24,2023-03-29,2023-03-23,FD,Flight Delay Coverage,0.0,2000.0,2000.0
3,4,30,NaN,NaN,GDF,7ด,180.0,2023-07-10,2023-07-21,2023-07-27,2023-08-07,2023-07-21,BD,Baggage Delay Coverage,0.0,0.0,0.0
4,5,50,NaN,NaN,GDF,7ด,180.0,2023-07-20,2023-07-25,2023-07-30,2023-08-03,2023-07-25,BD,Baggage Delay Coverage,0.0,6000.0,6000.0

In [136]:
# แปลงเป็น datetime โดยให้ pandas จัดการรูปแบบอัตโนมัติ
df_not_missing['DATESALE'] = pd.to_datetime(df_not_missing['DATESALE'], format='mixed', errors='coerce')
df_not_missing['INCDTE'] = pd.to_datetime(df_not_missing['INCDTE'], format='mixed', errors='coerce')

# คำนวณความต่างของวัน
df_not_missing['date_difference'] = (df_not_missing['INCDTE'] - df_not_missing['DATESALE']).dt.days

<ipython-input-136-58e63643be80>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['DATESALE'] = pd.to_datetime(df_not_missing['DATESALE'], format='mixed', errors='coerce')
<ipython-input-136-58e63643be80>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['INCDTE'] = pd.to_datetime(df_not_missing['INCDTE'], format='mixed', errors='coerce')
<ipython-input-136-58e63643be80>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_not_missing['date_difference'] = (df_not_missing['INCDTE'] - df_not_missing['DATESALE']).dt.days

In [137]:
df_not_missing.head()

,Dummy ID,AGE,SEX,Occupation,Policy_Class,Plan_,Premium,DATESALE,INCDTE,ExpireDate,DATREP,DATOCC,ReserveCode,ReseveDescription,GRS_OS,GRS_PAID,GIC,date_difference
0,1,40,NaN,NaN,GDF,7U,80.0,2022-12-11,2022-12-31,2023-01-01,2023-07-11,2023-01-01,VD,ค่ารักษาจากโควิค19,0.0,0.0,0.0,20
1,2,75,NaN,EMPLOYEE,GDF,8Y,160.0,2022-12-31,2023-01-24,2023-01-28,2023-03-08,2023-01-27,FD,Flight Delay Coverage,0.0,2000.0,2000.0,24
2,3,33,NaN,NaN,GDF,7ฉ,100.0,2023-03-23,2023-03-23,2023-03-24,2023-03-29,2023-03-23,FD,Flight Delay Coverage,0.0,2000.0,2000.0,0
3,4,30,NaN,NaN,GDF,7ด,180.0,2023-07-10,2023-07-21,2023-07-27,2023-08-07,2023-07-21,BD,Baggage Delay Coverage,0.0,0.0,0.0,11
4,5,50,NaN,NaN,GDF,7ด,180.0,2023-07-20,2023-07-25,2023-07-30,2023-08-03,2023-07-25,BD,Baggage Delay Coverage,0.0,6000.0,6000.0,5

⏰

df_missing

In [142]:
df_missing['DATESALE'] = pd.to_datetime(df_missing['DATESALE']).dt.strftime('%Y-%m-%d')

<ipython-input-142-e4e45b614958>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['DATESALE'] = pd.to_datetime(df_missing['DATESALE']).dt.strftime('%Y-%m-%d')

In [143]:
# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df_missing['INCDTE'] = pd.to_datetime(df_missing['INCDTE'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df_missing['INCDTE'] = df_missing['INCDTE'].dt.strftime('%Y-%m-%d')

# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df_missing['ExpireDate'] = pd.to_datetime(df_missing['ExpireDate'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df_missing['ExpireDate'] = df_missing['ExpireDate'].dt.strftime('%Y-%m-%d')

# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df_missing['DATREP'] = pd.to_datetime(df_missing['DATREP'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df_missing['DATREP'] = df_missing['DATREP'].dt.strftime('%Y-%m-%d')

# แปลงเป็น string แล้วค่อยแปลงเป็น datetime
df_missing['DATOCC'] = pd.to_datetime(df_missing['DATOCC'].astype(str), format='%Y%m%d')
# แปลงเป็นรูปแบบ YYYY-MM-DD
df_missing['DATOCC'] = df_missing['DATOCC'].dt.strftime('%Y-%m-%d')

<ipython-input-143-6a0ac9b915f5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['INCDTE'] = pd.to_datetime(df_missing['INCDTE'].astype(str), format='%Y%m%d')
<ipython-input-143-6a0ac9b915f5>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['INCDTE'] = df_missing['INCDTE'].dt.strftime('%Y-%m-%d')
<ipython-input-143-6a0ac9b915f5>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['ExpireDate'] = pd.to_datetime(df_missing['ExpireDate'].astype(str), format='%Y%m%d')
<ipython-input-143-6a0ac9b915f5>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['ExpireDate'] = df_missing['ExpireDate'].dt.strftime('%Y-%m-%d')
<ipython-input-143-6a0ac9b915f5>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['DATREP'] = pd.to_datetime(df_missing['DATREP'].astype(str), format='%Y%m%d')
<ipython-input-143-6a0ac9b915f5>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['DATREP'] = df_missing['DATREP'].dt.strftime('%Y-%m-%d')
<ipython-input-143-6a0ac9b915f5>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['DATOCC'] = pd.to_datetime(df_missing['DATOCC'].astype(str), format='%Y%m%d')
<ipython-input-143-6a0ac9b915f5>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['DATOCC'] = df_missing['DATOCC'].dt.strftime('%Y-%m-%d')

In [144]:
df_missing.head()

,Dummy ID,AGE,SEX,Occupation,Policy_Class,Plan_,Premium,DATESALE,INCDTE,ExpireDate,DATREP,DATOCC,ReserveCode,ReseveDescription,GRS_OS,GRS_PAID,GIC
30,41,0,NaN,NaN,GAT,NaN,1708.0,NaN,2023-03-24,2023-03-27,2023-04-10,2023-03-25,ME,GP/A Medical Expense,0.0,2407.0,2407.0
31,42,0,NaN,EMPLOYEE,GAT,NaN,1272.0,NaN,2024-10-21,2024-10-27,2024-11-18,2024-10-25,ME,GP/A Medical Expense,0.0,1202.0,1202.0
146,181,0,NaN,NaN,GAT,NaN,502.0,NaN,2023-02-10,2023-02-13,2023-03-15,2023-02-11,ME,GP/A Medical Expense,0.0,0.0,0.0
147,182,0,NaN,NaN,GAT,NaN,4200.0,NaN,2023-03-10,2023-03-13,2023-04-12,2023-03-10,ME,GP/A Medical Expense,0.0,1680.0,1680.0
148,183,0,NaN,EMPLOYEE,GAT,NaN,19980.0,NaN,2023-11-10,2023-11-12,2023-11-24,2023-11-10,ME,GP/A Medical Expense,0.0,23690.0,23690.0

In [145]:
# แปลงค่าใน 'INCDTE' เป็น datetime
df_missing['INCDTE'] = pd.to_datetime(df_missing['INCDTE'])

# สุ่มตัวเลขจาก 1 ถึง 332 สำหรับ DataFrame df_missing
df_missing['random_days'] = np.random.choice(range(1, 333), size=len(df_missing))

# หักลบจำนวนวันจาก 'INCDTE'
df_missing['DATESALE'] = df_missing['INCDTE'] - pd.to_timedelta(df_missing['random_days'], unit='D')

# แสดงผล
print(df_missing[['INCDTE', 'random_days', 'DATESALE']])

         INCDTE  random_days   DATESALE
30   2023-03-24          234 2022-08-02
31   2024-10-21           18 2024-10-03
146  2023-02-10           48 2022-12-24
147  2023-03-10          311 2022-05-03
148  2023-11-10          203 2023-04-21
...         ...          ...        ...
9817 2023-07-21          252 2022-11-11
9818 2023-07-21          277 2022-10-17
9819 2024-07-17            4 2024-07-13
9820 2024-07-17          263 2023-10-28
9821 2024-07-19          167 2024-02-03

[543 rows x 3 columns]

<ipython-input-145-c1b28bdf196c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['INCDTE'] = pd.to_datetime(df_missing['INCDTE'])
<ipython-input-145-c1b28bdf196c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['random_days'] = np.random.choice(range(1, 333), size=len(df_missing))
<ipython-input-145-c1b28bdf196c>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_missing['DATESALE'] = df_missing['INCDTE'] - pd.to_timedelta(df_missing['random_days'], unit='D')

In [146]:
df_missing

,Dummy ID,AGE,SEX,Occupation,Policy_Class,Plan_,Premium,DATESALE,INCDTE,ExpireDate,DATREP,DATOCC,ReserveCode,ReseveDescription,GRS_OS,GRS_PAID,GIC,random_days
30,41,0,NaN,NaN,GAT,NaN,1708.0,2022-08-02,2023-03-24,2023-03-27,2023-04-10,2023-03-25,ME,GP/A Medical Expense,0.00,2407.00,2407.00,234
31,42,0,NaN,EMPLOYEE,GAT,NaN,1272.0,2024-10-03,2024-10-21,2024-10-27,2024-11-18,2024-10-25,ME,GP/A Medical Expense,0.00,1202.00,1202.00,18
146,181,0,NaN,NaN,GAT,NaN,502.0,2022-12-24,2023-02-10,2023-02-13,2023-03-15,2023-02-11,ME,GP/A Medical Expense,0.00,0.00,0.00,48
147,182,0,NaN,NaN,GAT,NaN,4200.0,2022-05-03,2023-03-10,2023-03-13,2023-04-12,2023-03-10,ME,GP/A Medical Expense,0.00,1680.00,1680.00,311
148,183,0,NaN,EMPLOYEE,GAT,NaN,19980.0,2023-04-21,2023-11-10,2023-11-12,2023-11-24,2023-11-10,ME,GP/A Medical Expense,0.00,23690.00,23690.00,203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9817,10311,43,NaN,EMPLOYEE,GWW,NaN,208618.0,2022-11-11,2023-07-21,2023-09-26,2023-12-20,2023-08-02,ME,GP/A Medical Expense,0.00,166945.50,166945.50,252
9818,10312,25,NaN,EMPLOYEE,GWW,NaN,154123.0,2022-10-17,2023-07-21,2023-09-26,2023-12-20,2023-08-01,ME,GP/A Medical Expense,0.00,9536.86,9536.86,277
9819,10313,44,NaN,EMPLOYEE,GWW,NaN,255796.0,2024-07-13,2024-07-17,2024-09-30,2025-01-29,2024-09-02,ME,GP/A Medical Expense,1816.52,0.00,1816.52,4
9820,10314,50,NaN,EMPLOYEE,GWW,NaN,255796.0,2023-10-28,2024-07-17,2024-09-30,2025-01-29,2024-08-28,ME,GP/A Medical Expense,14333.83,0.00,14333.83,263
9821,10315,54,NaN,EMPLOYEE,GWW,NaN,250747.0,2024-02-03,2024-07-19,2024-10-02,2025-01-29,2024-08-19,ME,GP/A Medical Expense,8605.21,0.00,8605.21,167

In [152]:
df_missing.to_excel('df_missing.xlsx', index=False)