<a href="https://colab.research.google.com/github/Suchada2000/MY-WORK/blob/main/Untitled18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# เอาข้อมูลเข้า + แบ่งฝึกกับทดสอบ

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [83]:
df = pd.read_excel('/content/drive/MyDrive/project/example.xlsx')

In [84]:
#include relevant columns within x and y
x = df.iloc[:, 1:13]
y = df.iloc[:, 13]
df.head()
#ตัวแปรต้นเริ่มจาก Age-Time
#ตัวแปรตาม result

,ID,Age,Gender,Career,No_policy,No_claim,Insurance premium,Result_claim,Payment,Time_information,Conversation,Speed,Time,result
0,1,30,m,1,2,1,3000,claim,on time,1,normal,1,1,honest
1,2,35,f,4,2,2,5000,claim,late,0,normal,5,2,Fraud
2,3,21,f,5,3,2,1500,reject,on time,0,normal,3,5,honest
3,4,25,f,3,3,1,3500,reject,on time,0,bad,2,4,honest
4,5,40,f,1,3,3,4000,claim,late,2,normal,1,2,honest

# เปลี่ยนชนิดให้เป็นตัวเลข

In [88]:
#apply encoder on Gender as well
labelencoder_x_2 = LabelEncoder()
x.iloc[:, 1] = labelencoder_x_2.fit_transform(x.iloc[:, 1])
x.iloc[:, 6] = labelencoder_x_2.fit_transform(x.iloc[:, 6]) #applying on Gender
x.iloc[:, 7] = labelencoder_x_2.fit_transform(x.iloc[:, 7])
x.iloc[:, 9] = labelencoder_x_2.fit_transform(x.iloc[:, 9])
x.head()
#เปลี่ยนชนิดของคอลัมที่ 2 ในตัวอย่างคือ gender นับ 0 1 2 แต่ที่เราทำเป็นการเลือกหลายคอลัม แต่ถ้าอยากเลือกแค่คอลัมเดียวก็ให้ใช้วิธีนี้

,Age,Gender,Career,No_policy,No_claim,Insurance premium,Result_claim,Payment,Time_information,Conversation,Speed,Time
0,30,0,1,2,1,3000,0,1,1,1,1,1
1,35,0,4,2,2,5000,0,0,0,1,5,2
2,21,1,5,3,2,1500,1,1,0,1,3,5
3,25,1,3,3,1,3500,1,1,0,0,2,4
4,40,0,1,3,3,4000,0,0,2,1,1,2

In [89]:

x = df.drop(['result'], axis=1)

y = df['result']
#แบ่งว่าตัสแปรไหนคือฝึกหรือทดสอบ

In [90]:
x

,ID,Age,Gender,Career,No_policy,No_claim,Insurance premium,Result_claim,Payment,Time_information,Conversation,Speed,Time
0,1,30,m,1,2,1,3000,claim,on time,1,normal,1,1
1,2,35,f,4,2,2,5000,claim,late,0,normal,5,2
2,3,21,f,5,3,2,1500,reject,on time,0,normal,3,5
3,4,25,f,3,3,1,3500,reject,on time,0,bad,2,4
4,5,40,f,1,3,3,4000,claim,late,2,normal,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,65,f,5,3,2,1500,reject,on time,0,normal,3,5
96,97,2,m,3,3,1,3500,reject,on time,0,bad,2,4
97,98,23,f,8,3,3,4000,claim,late,2,normal,1,2
98,99,22,m,2,1,1,5000,claim,on time,0,normal,2,8
99,100,28,f,9,3,2,1500,reject,late,1,bad,7,4

In [91]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.40, random_state = 42)
#จะแบ่งเป็นกี่ %
#ชุดทดสอบเป็น 40% 42 เพื่อให้ได้ผลลัพธ์เหมือนเดิมทุกครั้งที่รันโค้ด

In [92]:

x_train

,ID,Age,Gender,Career,No_policy,No_claim,Insurance premium,Result_claim,Payment,Time_information,Conversation,Speed,Time
49,50,28,f,3,2,1,3500,claim,on time,2,normal,3,2
34,35,20,f,3,2,1,3500,claim,on time,2,normal,3,2
7,8,57,f,3,2,1,3500,claim,on time,2,normal,3,2
95,96,65,f,5,3,2,1500,reject,on time,0,normal,3,5
27,28,67,f,1,2,1,3000,claim,on time,1,normal,1,1
19,20,3,f,8,1,1,5000,claim,on time,0,normal,2,8
81,82,21,f,1,3,2,2500,reject,late,0,normal,2,4
25,26,45,m,3,3,1,3500,reject,on time,0,bad,2,4
62,63,20,m,8,1,1,5000,claim,on time,0,normal,2,8
13,14,21,f,3,3,1,3500,reject,on time,0,bad,2,4
24,25,22,f,5,3,2,1500,reject,on time,0,normal,3,5
3,4,25,f,3,3,1,3500,reject,on time,0,bad,2,4
17,18,21,f,3,3,1,3500,reject,on time,0,bad,2,4
38,39,3,m,4,2,2,5000,claim,late,0,normal,5,2
8,9,25,m,5,2,1,6500,reject,late,3,normal,5,1
78,79,22,f,9,3,2,1500,reject,late,1,bad,7,4
6,7,60,m,9,3,2,1500,reject,late,1,bad,7,4
64,65,45,m,3,2,1,3500,claim,on time,2,normal,3,2
36,37,6,m,1,3,2,2500,reject,late,0,normal,2,4
89,90,28,f,9,3,2,1500,reject,late,1,bad,7,4
56,57,2,m,8,3,3,4000,claim,late,2,normal,1,2
99,100,28,f,9,3,2,1500,reject,late,1,bad,7,4
54,55,45,f,5,3,2,1500,reject,on time,0,normal,3,5
43,44,23,f,9,3,2,1500,reject,late,1,bad,7,4
50,51,30,m,5,2,1,6500,reject,late,3,normal,5,1
67,68,23,f,1,2,1,3000,claim,on time,1,normal,1,1
46,47,2,m,1,3,2,2500,reject,late,0,normal,2,4
68,69,22,f,4,2,2,5000,claim,late,0,normal,5,2
61,62,21,m,1,3,2,2500,reject,late,0,normal,2,4
97,98,23,f,8,3,3,4000,claim,late,2,normal,1,2
79,80,28,m,3,2,1,3500,claim,on time,2,normal,3,2
41,42,45,f,8,3,3,4000,claim,late,2,normal,1,2
58,59,22,f,9,3,2,1500,reject,late,1,bad,7,4
48,49,22,m,9,3,2,1500,reject,late,1,bad,7,4
98,99,22,m,2,1,1,5000,claim,on time,0,normal,2,8
57,58,23,f,2,1,1,5000,claim,on time,0,normal,2,8
75,76,65,m,5,2,1,6500,reject,late,3,normal,5,1
32,33,43,f,8,1,1,5000,claim,on time,0,normal,2,8
94,95,45,m,4,2,2,5000,claim,late,0,normal,5,2
59,60,28,f,3,2,1,3500,claim,on time,2,normal,3,2
63,64,23,f,9,3,2,1500,reject,late,1,bad,7,4
84,85,45,m,5,3,2,1500,reject,on time,0,normal,3,5
37,38,65,f,1,2,1,3000,claim,on time,1,normal,1,1
29,30,21,f,5,3,2,1500,reject,on time,0,normal,3,5
1,2,35,f,4,2,2,5000,claim,late,0,normal,5,2
52,53,20,f,1,2,1,3000,claim,on time,1,normal,1,1
21,22,65,f,3,2,1,3500,claim,on time,2,normal,3,2
2,3,21,f,5,3,2,1500,reject,on time,0,normal,3,5
23,24,23,f,4,2,2,5000,claim,late,0,normal,5,2
87,88,23,m,2,1,1,5000,claim,on time,0,normal,2,8
91,92,21,f,5,2,1,6500,reject,late,3,normal,5,1
74,75,45,m,3,2,1,3500,claim,on time,2,normal,3,2
86,87,2,f,8,3,3,4000,claim,late,2,normal,1,2
82,83,20,f,1,2,1,3000,claim,on time,1,normal,1,1
20,21,6,m,9,3,2,1500,reject,late,1,bad,7,4
60,61,30,f,5,2,1,6500,reject,late,3,normal,5,1
71,72,21,f,8,3,3,4000,claim,late,2,normal,1,2
14,15,45,f,1,2,1,3000,claim,on time,1,normal,1,1
92,93,20,f,1,3,2,2500,reject,late,0,normal,2,4
51,52,21,f,1,3,2,2500,reject,late,0,normal,2,4

 One-Hot Encoding เป็นเทคนิคพื้นฐานในการเตรียมข้อมูลประเภทหมวดหมู่เพื่อใช้ในโมเดล Machine Learning โดยช่วยลดปัญหาเรื่องอคติของลำดับตัวเลขจาก Label Encoding. ถ้าข้อมูลมีแค่ 2 อย่างเช่นชายหญิง ก็ไม่จำเป็นต้องทำ มันเป็ฯวิธีทำให้คอลัมเพิ่มขึ้นแต่ค่าที่ได้จะมีแค่ 0 1 แต่คอลัมคนละจุดเลยมีความหมายที่ต่างกัน

 เป็นการทำในข้อมูลที่ไม่มีความหมายเชิงตัวเลขในตัวเช่น สี

In [67]:
from keras.utils import to_categorical
encoded = pd.DataFrame(to_categorical(x.iloc[:, 2]))
#, 1 คือจากคอลัมที่ 1 นับจาก 0 1
#no need to encode Gender, as there are only two categories
#ในที่นี้แบ่งของอาชีพเพราะอาชีพไม่มีลำดับเป็นของตัวเองและมีหมวดหมูมากกว่า 2 ไม่เหมือนเพศที่มีแค่ชาย หญิง

x = pd.concat([encoded, x], axis = 1)
x.head()

,0,1,0,0,1,0,1,2,3,4,...,Gender,No_policy,No_claim,Insurance premium,Result_claim,Payment,Time_information,Conversation,Speed,Time
0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,2,1,3000,0,1,1,1,1,1
1,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,2,2,5000,0,0,0,1,5,2
2,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,3,2,1500,1,1,0,1,3,5
3,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,3,1,3500,1,1,0,0,2,4
4,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,3,3,4000,0,0,2,1,1,2

In [22]:
df

,ID,Age,Gender,Career,No_policy,No_claim,Insurance premium,Result_claim,Payment,Time_information,Conversation,Speed,Time,result
0,1,30,1,1,2,1,3000,0,1,1,1,1,1,honest
1,2,35,0,4,2,2,5000,0,0,0,1,5,2,Fraud
2,3,21,0,5,3,2,1500,1,1,0,1,3,5,honest
3,4,25,0,3,3,1,3500,1,1,0,0,2,4,honest
4,5,40,0,1,3,3,4000,0,0,2,1,1,2,honest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,65,0,5,3,2,1500,1,1,0,1,3,5,honest
96,97,2,1,3,3,1,3500,1,1,0,0,2,4,honest
97,98,23,0,8,3,3,4000,0,0,2,1,1,2,honest
98,99,22,1,2,1,1,5000,0,1,0,1,2,8,honest
99,100,28,0,9,3,2,1500,1,0,1,0,7,4,Fraud

In [18]:
import keras
from keras.models import Sequential
from keras.layers import Dense #to add layers

#there is no rule on how many nodes each hidden layer should have
classifier = Sequential()
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
#init --> initialize weights according to uniform distribution
#input_dim is required for the first hidden layer, as it is the first starting point. --> number of nodes.
#output_dim --> number of nodes of the hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
#input_dim --> remove it as it already knows what to expect.

#the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))
#output_dim should be 1, as output is binary outcome, and activation should be 'sigmoid'
#If dependent variables have more than two categories, use activation = 'softmax'

#compile the model --> backpropagation -> gradient descent
classifier.compile(optimizer = 'adam', loss = "binary_crossentropy", metrics = ['accuracy'])
#optimizer = algorithm to find the optimal set of weights in ANN
#loss = functions that should be optimized. if more than two categories, use "categorical_crossentropy"
#metrics = criterion used to calculate the performance of the model.

TypeError: Dense.__init__() missing 1 required positional argument: 'units'